
import { ModelData } from './types';

export const MODELS: ModelData[] = [
  // --- MULTIMODAL ---
  {
    id: 'gemini-3-pro-preview',
    name: 'Gemini 3 Pro Preview',
    developer: 'Google DeepMind',
    releaseDate: '2025-09',
    category: 'Multimodal',
    price: 'Paid API',
    apiPrice: 'Paid',
    description: 'The world’s most capable AI model for complex tasks. Features massive context windows, advanced reasoning, coding, math, and native multimodal understanding.',
    features: ['Advanced Reasoning', 'Complex Coding', 'STEM Support', 'Native Multimodal'],
    badge: 'Flagship',
    tags: ['reasoning', 'coding', 'multimodal', 'google'],
    link: 'https://deepmind.google/technologies/gemini/'
  },
  {
    id: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    developer: 'Google DeepMind',
    releaseDate: '2025-08',
    category: 'Multimodal',
    price: 'Low Cost API',
    apiPrice: 'Low Cost',
    description: 'Optimized for speed and efficiency. Delivers sub-second latency for basic text tasks, summarization, proofreading, and simple Q&A.',
    features: ['Sub-second Latency', 'High Efficiency', 'Summarization', 'Proofreading'],
    badge: 'Fastest',
    tags: ['fast', 'efficient', 'multimodal', 'google'],
    link: 'https://deepmind.google/technologies/gemini/flash/'
  },
  {
    id: 'gemini-flash-lite-latest',
    name: 'Gemini 2.5 Flash-Lite',
    developer: 'Google DeepMind',
    releaseDate: '2025-08',
    category: 'Multimodal',
    price: 'Lowest Cost API',
    apiPrice: 'Lowest Cost',
    description: 'Engineered for high-frequency, cost-sensitive tasks. The perfect balance of performance and economy for high-volume applications.',
    features: ['Cost Efficient', 'High Throughput', 'Lite Architecture', 'Fast'],
    badge: 'Value',
    tags: ['lite', 'economy', 'multimodal', 'google'],
    link: 'https://deepmind.google/technologies/gemini/flash/'
  },
  {
    id: 'gpt-5',
    name: 'GPT-5 (Orion)',
    developer: 'OpenAI',
    releaseDate: '2025-10',
    category: 'Multimodal',
    price: '$20/mo',
    apiPrice: '$5.00 / 1M',
    description: 'The next leap in reasoning and agentic behavior. Deeply integrated with voice and visual capabilities for a seamless assistant experience.',
    features: ['Deep Reasoning', 'Agentic Capabilities', 'Voice Mode', 'Visual Analysis'],
    tags: ['reasoning', 'assistant', 'multimodal'],
    link: 'https://openai.com'
  },
  {
    id: 'claude-3-5-opus',
    name: 'Claude 3.5 Opus',
    developer: 'Anthropic',
    releaseDate: '2025-06',
    category: 'Multimodal',
    price: '$20/mo',
    apiPrice: '$15.00 / 1M',
    description: 'Unmatched nuance and creative writing capabilities. Features a massive 500k context window and improved artifact generation.',
    features: ['Nuance', 'Creative Writing', 'Large Context', 'Coding'],
    tags: ['creative', 'writing', 'multimodal'],
    link: 'https://anthropic.com'
  },
  {
    id: 'llama-4-405b',
    name: 'Llama 4 405B',
    developer: 'Meta',
    releaseDate: '2025-07',
    category: 'Multimodal',
    price: 'Open Source',
    apiPrice: 'Free (Self-hosted)',
    description: 'The state-of-the-art open weights model. Capable of complex reasoning and multilingual translation rivaling closed source models.',
    features: ['Open Source', 'Multilingual', 'Self-hostable', 'Reasoning'],
    tags: ['open-source', 'meta', 'multimodal'],
    link: 'https://llama.meta.com'
  },
  {
    id: 'grok-3',
    name: 'Grok 3',
    developer: 'xAI',
    releaseDate: '2025-08',
    category: 'Multimodal',
    price: '$16/mo',
    apiPrice: 'N/A',
    description: 'Real-time access to X (Twitter) data with reduced guardrails and a witty personality. Strong coding and math benchmarks.',
    features: ['Real-time Data', 'Uncensored', 'Coding', 'Wit'],
    tags: ['social', 'real-time', 'multimodal'],
    link: 'https://x.ai'
  },
  {
    id: 'mistral-large-2',
    name: 'Mistral Large 2',
    developer: 'Mistral AI',
    releaseDate: '2025-07',
    category: 'Multimodal',
    price: 'Paid API',
    apiPrice: 'Usage Based',
    description: 'Europe’s flagship model. exceptional coding performance and multilingual capabilities with a focus on efficiency.',
    features: ['Coding', 'Multilingual', 'Efficient', 'Function Calling'],
    tags: ['coding', 'european', 'multimodal'],
    link: 'https://mistral.ai'
  },

  // --- IMAGE ---
  {
    id: 'gemini-3-pro-image-preview',
    name: 'Gemini 3 Pro Image',
    developer: 'Google',
    releaseDate: '2025-09',
    category: 'Image',
    price: 'Paid API',
    apiPrice: 'Paid',
    description: 'High-Quality Image Generation and Editing Tasks. Supports 1K, 2K, and 4K resolution and Google Search grounding.',
    features: ['4K Resolution', 'Google Search', 'High Fidelity', 'Complex Prompts'],
    badge: 'High Res',
    tags: ['4k', 'professional', 'google-search', 'google'],
    link: 'https://deepmind.google'
  },
  {
    id: 'gemini-2.5-flash-image',
    name: 'Gemini 2.5 Flash Image',
    developer: 'Google',
    releaseDate: '2025-08',
    category: 'Image',
    price: 'Low Cost',
    apiPrice: 'Low Cost',
    description: 'The "Nano Banana" series. Optimized for general image generation and editing tasks with exceptional speed.',
    features: ['Fast Generation', 'Image Editing', 'General Purpose', 'Efficiency'],
    badge: 'Fast',
    tags: ['image', 'editing', 'fast', 'google'],
    link: 'https://deepmind.google'
  },
  {
    id: 'imagen-4.0-generate-001',
    name: 'Imagen 4',
    developer: 'Google',
    releaseDate: '2025-02',
    category: 'Image',
    price: '$0.04/img',
    apiPrice: '$0.04 / image',
    description: 'Google’s diffusion-based model with sharp visuals and accurate text rendering. High photorealism.',
    features: ['Sharp Visuals', 'Text Rendering', 'Graphic Gen', 'Photorealism'],
    tags: ['realistic', 'google', 'text'],
    link: 'https://deepmind.google/technologies/imagen/'
  },
  {
    id: 'midjourney-v7',
    name: 'Midjourney V7',
    developer: 'Midjourney',
    releaseDate: '2025-04',
    category: 'Image',
    price: '$10/mo',
    apiPrice: 'N/A',
    description: 'Complete architectural redesign with improved aesthetics, better body/hand coherence, and character reference features.',
    features: ['Character Reference', 'Draft Mode', 'Style Explorer', 'Texture Control'],
    badge: 'Aesthetic',
    tags: ['artistic', 'creative', 'consistency'],
    link: 'https://midjourney.com'
  },
  {
    id: 'flux-1.1-kontext',
    name: 'Flux 1.1 Kontext',
    developer: 'Black Forest Labs',
    releaseDate: '2025-05',
    category: 'Image',
    price: '$0.08/img',
    apiPrice: '$0.08 / image',
    description: 'Context-aware image generation and editing suite with exceptional precision and professional workflow support.',
    features: ['Context Aware', 'Style Transfer', 'Relighting', '4MP Ultra Res'],
    tags: ['professional', 'precise', 'editing'],
    link: 'https://blackforestlabs.ai'
  },
  {
    id: 'dall-e-4',
    name: 'DALL-E 4',
    developer: 'OpenAI',
    releaseDate: '2025-09',
    category: 'Image',
    price: '$20/mo',
    apiPrice: '$0.04 / img',
    description: 'Perfect instruction following and native text rendering. deeply integrated into ChatGPT for iterative editing.',
    features: ['Iterative Editing', 'Text Rendering', 'Simple Prompting', 'Chat Integration'],
    tags: ['easy', 'chat', 'text'],
    link: 'https://openai.com/dall-e-4'
  },
  {
    id: 'sd-3-5-large',
    name: 'Stable Diffusion 3.5',
    developer: 'Stability AI',
    releaseDate: '2024-12',
    category: 'Image',
    price: 'Open Weights',
    apiPrice: 'Self-hosted',
    description: 'The most capable open model for photorealism and typography. Highly optimizable and runnable on consumer hardware.',
    features: ['Open Weights', 'Typography', 'Photorealism', 'Fine-tunable'],
    tags: ['open-source', 'stable-diffusion', 'local'],
    link: 'https://stability.ai'
  },
  {
    id: 'leonardo-phoenix-2',
    name: 'Leonardo Phoenix 2',
    developer: 'Leonardo.ai',
    releaseDate: '2025-03',
    category: 'Image',
    price: 'Freemium',
    apiPrice: 'N/A',
    description: 'Game asset focused generation with transparency support and 3D texture map estimation.',
    features: ['Game Assets', 'Transparency', 'Texture Maps', 'Style Consistent'],
    tags: ['game-dev', 'assets', 'art'],
    link: 'https://leonardo.ai'
  },

  // --- VIDEO ---
  {
    id: 'veo-3.1-generate-preview',
    name: 'Veo 3.1',
    developer: 'Google DeepMind',
    releaseDate: '2025-10',
    category: 'Video',
    price: 'Paid API',
    apiPrice: 'Paid',
    description: 'High-Quality Video Generation. Supports reference images (character consistency), video extension, and cinematic effects.',
    features: ['High Quality', 'Video Extension', 'Reference Images', 'Cinematic'],
    badge: 'Cinema Grade',
    tags: ['video', 'production', 'google', 'editing'],
    link: 'https://deepmind.google/technologies/veo/'
  },
  {
    id: 'veo-3.1-fast-generate-preview',
    name: 'Veo 3.1 Fast',
    developer: 'Google DeepMind',
    releaseDate: '2025-10',
    category: 'Video',
    price: 'Low Cost',
    apiPrice: 'Low Cost',
    description: 'General Video Generation. Optimized for speed and rapid prototyping.',
    features: ['Fast Generation', 'General Purpose', 'Rapid Prototyping'],
    tags: ['fast', 'video', 'google'],
    link: 'https://deepmind.google/technologies/veo/'
  },
  {
    id: 'sora-2',
    name: 'Sora 2',
    developer: 'OpenAI',
    releaseDate: '2025-01',
    category: 'Video',
    price: '$20/mo',
    apiPrice: '$0.10 / sec',
    description: 'Industry-leading photorealistic video up to 1 minute. Cinematic B-Roll and storyboard interface.',
    features: ['1 Minute Gen', 'Hyper-Realistic', 'Storyboard', 'Cinematic'],
    badge: 'Photorealism',
    tags: ['cinematic', 'realistic', 'professional'],
    link: 'https://openai.com/sora'
  },
  {
    id: 'runway-gen-4',
    name: 'Runway Gen-4',
    developer: 'Runway AI',
    releaseDate: '2024-11',
    category: 'Video',
    price: '$12/mo',
    apiPrice: '$0.05 / sec',
    description: 'Professional controls for filmmakers. Camera pathing, director mode, and advanced zoom/tilt controls.',
    features: ['Director Mode', 'Camera Control', 'Lip-Sync', '24 FPS'],
    tags: ['professional', 'editing', 'control'],
    link: 'https://runwayml.com'
  },
  {
    id: 'hailuo-video',
    name: 'Hailuo Video (MiniMax)',
    developer: 'MiniMax',
    releaseDate: '2024-12',
    category: 'Video',
    price: 'Free (Beta)',
    apiPrice: 'N/A',
    description: 'Impressive character movement and temporal consistency. Known for high quality human animation.',
    features: ['Character Motion', 'High FPS', 'Consistency', 'Human Animation'],
    tags: ['animation', 'character', 'video'],
    link: 'https://hailuo.ai'
  },
  {
    id: 'kling-1.5',
    name: 'Kling 1.5',
    developer: 'Kuaishou',
    releaseDate: '2024-12',
    category: 'Video',
    price: 'Credits',
    apiPrice: 'N/A',
    description: 'Capable of generating 2-minute videos at 1080p/60fps. Excellent physics simulation for complex scenes.',
    features: ['2 Minute Duration', '1080p 60fps', 'Physics', 'Long Form'],
    badge: 'Long Form',
    tags: ['long-video', 'physics', 'high-fps'],
    link: 'https://kling.kuaishou.com'
  },
  {
    id: 'luma-dream-machine-2',
    name: 'Luma Dream Machine 2',
    developer: 'Luma AI',
    releaseDate: '2025-01',
    category: 'Video',
    price: 'Freemium',
    apiPrice: 'Usage Based',
    description: 'Fast, high-quality video generation with keyframe control and loop creation tools.',
    features: ['Keyframes', 'Looping', 'Fast Gen', 'Image-to-Video'],
    tags: ['fast', 'loop', 'creative'],
    link: 'https://lumalabs.ai'
  },
  {
    id: 'pika-2-0',
    name: 'Pika 2.0',
    developer: 'Pika Labs',
    releaseDate: '2025-02',
    category: 'Video',
    price: 'Freemium',
    apiPrice: 'N/A',
    description: 'Specialized in anime and stylized animation with granular lip-sync and modify region tools.',
    features: ['Lip Sync', 'Modify Region', 'Anime Style', 'Sound Effects'],
    tags: ['anime', 'style', 'animation'],
    link: 'https://pika.art'
  },

  // --- AUDIO ---
  {
    id: 'gemini-2.5-flash-native-audio-preview-09-2025',
    name: 'Gemini 2.5 Flash Audio',
    developer: 'Google DeepMind',
    releaseDate: '2025-09',
    category: 'Audio',
    price: 'API',
    apiPrice: 'Usage Based',
    description: 'Native audio capabilities for real-time audio and video conversation tasks. Supports low latency interactions.',
    features: ['Real-time', 'Native Audio', 'Low Latency', 'Conversational'],
    badge: 'Real-Time',
    tags: ['audio', 'conversation', 'realtime', 'google'],
    link: 'https://deepmind.google'
  },
  {
    id: 'gemini-2.5-flash-preview-tts',
    name: 'Gemini 2.5 Flash TTS',
    developer: 'Google DeepMind',
    releaseDate: '2025-09',
    category: 'Audio',
    price: 'API',
    apiPrice: 'Usage Based',
    description: 'Text-to-speech capabilities for transforming text into single or multi-speaker audio.',
    features: ['Text-to-Speech', 'Multi-Speaker', 'Natural Voices', 'TTS'],
    tags: ['tts', 'speech', 'google'],
    link: 'https://deepmind.google'
  },
  {
    id: 'suno-v5',
    name: 'Suno v5',
    developer: 'Suno',
    releaseDate: '2025-09',
    category: 'Audio',
    price: '$10/mo',
    apiPrice: 'N/A',
    description: 'Studio-grade fidelity with natural vocals. Full song generation with lyrics and persona memory.',
    features: ['Full Songs', 'Lyrics', 'Stem Split', 'Personas'],
    badge: 'Studio Grade',
    tags: ['music', 'vocals', 'production'],
    link: 'https://suno.com'
  },
  {
    id: 'eleven-music',
    name: 'Eleven Music',
    developer: 'ElevenLabs',
    releaseDate: '2025-08',
    category: 'Audio',
    price: '$11/mo',
    apiPrice: '$0.50 / min',
    description: 'Industry-leading vocal synthesis with music generation. Strong instrumentals and commercial rights.',
    features: ['Vocal Synthesis', 'Instrumentals', 'Commercial Use', 'High Fidelity'],
    tags: ['vocals', 'sfx', 'production'],
    link: 'https://elevenlabs.io'
  },
  {
    id: 'udio-v2',
    name: 'Udio v2',
    developer: 'Udio',
    releaseDate: '2025-05',
    category: 'Audio',
    price: 'Freemium',
    apiPrice: 'N/A',
    description: 'Complex musical composition with high structural coherence. Excellent for electronic and classical genres.',
    features: ['Composition', 'Structure', 'Remixing', 'Extend Track'],
    tags: ['composition', 'music', 'electronic'],
    link: 'https://udio.com'
  },
  {
    id: 'stable-audio-2',
    name: 'Stable Audio 2',
    developer: 'Stability AI',
    releaseDate: '2024-04',
    category: 'Audio',
    price: 'Freemium',
    apiPrice: 'Usage Based',
    description: 'Generates full tracks up to 3 minutes with coherent structure. Strong sound effect generation.',
    features: ['Sound Effects', '3 Min Tracks', 'Structure', 'Audio-to-Audio'],
    tags: ['sfx', 'background', 'music'],
    link: 'https://stability.ai'
  }
];
