
import { ModelData } from './types';

export const MODELS: ModelData[] = [
  // --- MULTIMODAL ---
  {
    id: 'gemini-3-pro-preview',
    name: 'Gemini 3 Pro Preview',
    developer: 'Google DeepMind',
    releaseDate: '2025-09',
    category: 'Multimodal',
    price: 'Paid API',
    apiPrice: 'Paid',
    description: 'The world’s most capable AI model for complex tasks. Features massive context windows, advanced reasoning, coding, math, and native multimodal understanding.',
    features: ['Advanced Reasoning', 'Complex Coding', 'STEM Support', 'Native Multimodal'],
    badge: 'Flagship',
    tags: ['reasoning', 'coding', 'multimodal', 'google'],
    link: 'https://deepmind.google/technologies/gemini/'
  },
  {
    id: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    developer: 'Google DeepMind',
    releaseDate: '2025-08',
    category: 'Multimodal',
    price: 'Low Cost API',
    apiPrice: 'Low Cost',
    description: 'Optimized for speed and efficiency. Delivers sub-second latency for basic text tasks, summarization, proofreading, and simple Q&A.',
    features: ['Sub-second Latency', 'High Efficiency', 'Summarization', 'Proofreading'],
    badge: 'Fastest',
    tags: ['fast', 'efficient', 'multimodal', 'google'],
    link: 'https://deepmind.google/technologies/gemini/flash/'
  },
  {
    id: 'gemini-flash-lite-latest',
    name: 'Gemini 2.5 Flash-Lite',
    developer: 'Google DeepMind',
    releaseDate: '2025-08',
    category: 'Multimodal',
    price: 'Lowest Cost API',
    apiPrice: 'Lowest Cost',
    description: 'Engineered for high-frequency, cost-sensitive tasks. The perfect balance of performance and economy for high-volume applications.',
    features: ['Cost Efficient', 'High Throughput', 'Lite Architecture', 'Fast'],
    badge: 'Value',
    tags: ['lite', 'economy', 'multimodal', 'google'],
    link: 'https://deepmind.google/technologies/gemini/flash/'
  },
  {
    id: 'gpt-5',
    name: 'GPT-5 (Orion)',
    developer: 'OpenAI',
    releaseDate: '2025-10',
    category: 'Multimodal',
    price: '$20/mo',
    apiPrice: '$5.00 / 1M',
    description: 'The next leap in reasoning and agentic behavior. Deeply integrated with voice and visual capabilities for a seamless assistant experience.',
    features: ['Deep Reasoning', 'Agentic Capabilities', 'Voice Mode', 'Visual Analysis'],
    tags: ['reasoning', 'assistant', 'multimodal'],
    link: 'https://openai.com'
  },

  // --- IMAGE ---
  {
    id: 'gemini-3-pro-image-preview',
    name: 'Gemini 3 Pro Image',
    developer: 'Google',
    releaseDate: '2025-09',
    category: 'Image',
    price: 'Paid API',
    apiPrice: 'Paid',
    description: 'High-Quality Image Generation and Editing Tasks. Supports 1K, 2K, and 4K resolution and Google Search grounding.',
    features: ['4K Resolution', 'Google Search', 'High Fidelity', 'Complex Prompts'],
    badge: 'High Res',
    tags: ['4k', 'professional', 'google-search', 'google'],
    link: 'https://deepmind.google'
  },
  {
    id: 'gemini-2.5-flash-image',
    name: 'Gemini 2.5 Flash Image',
    developer: 'Google',
    releaseDate: '2025-08',
    category: 'Image',
    price: 'Low Cost',
    apiPrice: 'Low Cost',
    description: 'The "Nano Banana" series. Optimized for general image generation and editing tasks with exceptional speed.',
    features: ['Fast Generation', 'Image Editing', 'General Purpose', 'Efficiency'],
    badge: 'Fast',
    tags: ['image', 'editing', 'fast', 'google'],
    link: 'https://deepmind.google'
  },
  {
    id: 'imagen-4.0-generate-001',
    name: 'Imagen 4',
    developer: 'Google',
    releaseDate: '2025-02',
    category: 'Image',
    price: '$0.04/img',
    apiPrice: '$0.04 / image',
    description: 'Google’s diffusion-based model with sharp visuals and accurate text rendering. High photorealism.',
    features: ['Sharp Visuals', 'Text Rendering', 'Graphic Gen', 'Photorealism'],
    tags: ['realistic', 'google', 'text'],
    link: 'https://deepmind.google/technologies/imagen/'
  },
  {
    id: 'midjourney-v7',
    name: 'Midjourney V7',
    developer: 'Midjourney',
    releaseDate: '2025-04',
    category: 'Image',
    price: '$10/mo',
    apiPrice: 'N/A',
    description: 'Complete architectural redesign with improved aesthetics, better body/hand coherence, and character reference features.',
    features: ['Character Reference', 'Draft Mode', 'Style Explorer', 'Texture Control'],
    badge: 'Aesthetic',
    tags: ['artistic', 'creative', 'consistency'],
    link: 'https://midjourney.com'
  },
  {
    id: 'flux-1.1-kontext',
    name: 'Flux 1.1 Kontext',
    developer: 'Black Forest Labs',
    releaseDate: '2025-05',
    category: 'Image',
    price: '$0.08/img',
    apiPrice: '$0.08 / image',
    description: 'Context-aware image generation and editing suite with exceptional precision and professional workflow support.',
    features: ['Context Aware', 'Style Transfer', 'Relighting', '4MP Ultra Res'],
    tags: ['professional', 'precise', 'editing'],
    link: 'https://blackforestlabs.ai'
  },

  // --- VIDEO ---
  {
    id: 'veo-3.1-generate-preview',
    name: 'Veo 3.1',
    developer: 'Google DeepMind',
    releaseDate: '2025-10',
    category: 'Video',
    price: 'Paid API',
    apiPrice: 'Paid',
    description: 'High-Quality Video Generation. Supports reference images (character consistency), video extension, and cinematic effects.',
    features: ['High Quality', 'Video Extension', 'Reference Images', 'Cinematic'],
    badge: 'Cinema Grade',
    tags: ['video', 'production', 'google', 'editing'],
    link: 'https://deepmind.google/technologies/veo/'
  },
  {
    id: 'veo-3.1-fast-generate-preview',
    name: 'Veo 3.1 Fast',
    developer: 'Google DeepMind',
    releaseDate: '2025-10',
    category: 'Video',
    price: 'Low Cost',
    apiPrice: 'Low Cost',
    description: 'General Video Generation. Optimized for speed and rapid prototyping.',
    features: ['Fast Generation', 'General Purpose', 'Rapid Prototyping'],
    tags: ['fast', 'video', 'google'],
    link: 'https://deepmind.google/technologies/veo/'
  },
  {
    id: 'sora-2',
    name: 'Sora 2',
    developer: 'OpenAI',
    releaseDate: '2025-01',
    category: 'Video',
    price: '$20/mo',
    apiPrice: '$0.10 / sec',
    description: 'Industry-leading photorealistic video up to 1 minute. Cinematic B-Roll and storyboard interface.',
    features: ['1 Minute Gen', 'Hyper-Realistic', 'Storyboard', 'Cinematic'],
    badge: 'Photorealism',
    tags: ['cinematic', 'realistic', 'professional'],
    link: 'https://openai.com/sora'
  },
  {
    id: 'runway-gen-4',
    name: 'Runway Gen-4',
    developer: 'Runway AI',
    releaseDate: '2024-11',
    category: 'Video',
    price: '$12/mo',
    apiPrice: '$0.05 / sec',
    description: 'Professional controls for filmmakers. Camera pathing, director mode, and advanced zoom/tilt controls.',
    features: ['Director Mode', 'Camera Control', 'Lip-Sync', '24 FPS'],
    tags: ['professional', 'editing', 'control'],
    link: 'https://runwayml.com'
  },

  // --- AUDIO ---
  {
    id: 'gemini-2.5-flash-native-audio-preview-09-2025',
    name: 'Gemini 2.5 Flash Audio',
    developer: 'Google DeepMind',
    releaseDate: '2025-09',
    category: 'Audio',
    price: 'API',
    apiPrice: 'Usage Based',
    description: 'Native audio capabilities for real-time audio and video conversation tasks. Supports low latency interactions.',
    features: ['Real-time', 'Native Audio', 'Low Latency', 'Conversational'],
    badge: 'Real-Time',
    tags: ['audio', 'conversation', 'realtime', 'google'],
    link: 'https://deepmind.google'
  },
  {
    id: 'gemini-2.5-flash-preview-tts',
    name: 'Gemini 2.5 Flash TTS',
    developer: 'Google DeepMind',
    releaseDate: '2025-09',
    category: 'Audio',
    price: 'API',
    apiPrice: 'Usage Based',
    description: 'Text-to-speech capabilities for transforming text into single or multi-speaker audio.',
    features: ['Text-to-Speech', 'Multi-Speaker', 'Natural Voices', 'TTS'],
    tags: ['tts', 'speech', 'google'],
    link: 'https://deepmind.google'
  },
  {
    id: 'suno-v5',
    name: 'Suno v5',
    developer: 'Suno',
    releaseDate: '2025-09',
    category: 'Audio',
    price: '$10/mo',
    apiPrice: 'N/A',
    description: 'Studio-grade fidelity with natural vocals. Full song generation with lyrics and persona memory.',
    features: ['Full Songs', 'Lyrics', 'Stem Split', 'Personas'],
    badge: 'Studio Grade',
    tags: ['music', 'vocals', 'production'],
    link: 'https://suno.com'
  },
  {
    id: 'eleven-music',
    name: 'Eleven Music',
    developer: 'ElevenLabs',
    releaseDate: '2025-08',
    category: 'Audio',
    price: '$11/mo',
    apiPrice: '$0.50 / min',
    description: 'Industry-leading vocal synthesis with music generation. Strong instrumentals and commercial rights.',
    features: ['Vocal Synthesis', 'Instrumentals', 'Commercial Use', 'High Fidelity'],
    tags: ['vocals', 'sfx', 'production'],
    link: 'https://elevenlabs.io'
  }
];
