
import { ModelData } from './types';

export const MODELS: ModelData[] = [
  // --- MULTIMODAL MODELS ---
  {
    id: 'gemini-3-pro',
    name: 'Gemini 3 Pro',
    developer: 'Google DeepMind',
    releaseDate: '2025-09',
    category: 'Multimodal',
    price: 'Free / API Paid',
    apiPrice: '$2.50 / 1M input',
    description: 'The world’s most capable AI model for complex tasks. Features massive context windows, advanced reasoning, and native multimodal understanding across text, images, and video.',
    features: ['2M+ Token Context', 'Advanced Reasoning', 'Native Multimodal', 'Complex Coding'],
    badge: 'Flagship 2025',
    tags: ['reasoning', 'coding', 'multimodal', 'google'],
    link: 'https://deepmind.google/technologies/gemini/'
  },
  {
    id: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    developer: 'Google DeepMind',
    releaseDate: '2025-08',
    category: 'Multimodal',
    price: 'Low Cost API',
    apiPrice: '$0.075 / 1M input',
    description: 'Optimized for speed and efficiency. Delivers sub-second latency for high-volume tasks while maintaining exceptional reasoning capabilities.',
    features: ['Sub-second Latency', 'High Efficiency', 'Cost Effective', '1M Token Context'],
    badge: 'Fastest',
    tags: ['fast', 'efficient', 'multimodal', 'api'],
    link: 'https://deepmind.google/technologies/gemini/flash/'
  },
  {
    id: 'gpt-5',
    name: 'GPT-5 (Orion)',
    developer: 'OpenAI',
    releaseDate: '2025-10',
    category: 'Multimodal',
    price: '$20/mo',
    apiPrice: '$5.00 / 1M input',
    description: 'The next leap in reasoning and agentic behavior. Deeply integrated with voice and visual capabilities for a seamless assistant experience.',
    features: ['Deep Reasoning', 'Agentic Capabilities', 'Voice Mode', 'Visual Analysis'],
    tags: ['reasoning', 'assistant', 'multimodal'],
    link: 'https://openai.com'
  },

  // --- IMAGE MODELS ---
  {
    id: 'gemini-nano-banana',
    name: 'Nano Banana',
    developer: 'Google',
    releaseDate: '2025-08',
    category: 'Image',
    price: '$0.039/img',
    apiPrice: '$0.039 / image',
    description: 'Gemini 2.5 Flash Image. Google’s latest model with exceptional character consistency across multiple edits and conversational editing capabilities.',
    features: ['Character Consistency', 'Natural Language Edit', '9s Generation', 'Face Preservation'],
    badge: 'Consistency',
    tags: ['image', 'editing', 'fast', 'google'],
    link: 'https://deepmind.google'
  },
  {
    id: 'flux-1.1-kontext',
    name: 'Flux 1.1 Kontext Max',
    developer: 'Black Forest Labs',
    releaseDate: '2025-05',
    category: 'Image',
    price: '$0.08/img',
    apiPrice: '$0.08 / image',
    description: 'Context-aware image generation and editing suite with exceptional precision and professional workflow support.',
    features: ['Context Aware', 'Style Transfer', 'Relighting', '4MP Ultra Res'],
    badge: 'Pro Choice',
    tags: ['professional', 'precise', 'editing'],
    link: 'https://blackforestlabs.ai'
  },
  {
    id: 'midjourney-v7',
    name: 'Midjourney V7',
    developer: 'Midjourney',
    releaseDate: '2025-04',
    category: 'Image',
    price: '$10/mo',
    apiPrice: 'N/A',
    description: 'Complete architectural redesign with improved aesthetics, better body/hand coherence, and character reference features.',
    features: ['Character Reference', 'Draft Mode', 'Style Explorer', 'Texture Control'],
    badge: 'Aesthetic',
    tags: ['artistic', 'creative', 'consistency'],
    link: 'https://midjourney.com'
  },
  {
    id: 'mai-image-1',
    name: 'MAI-Image-1',
    developer: 'Microsoft',
    releaseDate: '2025-11',
    category: 'Image',
    price: 'Free',
    apiPrice: 'Usage Based',
    description: 'Microsoft’s first proprietary image generator excelling in food photography, natural scenes, and lighting effects.',
    features: ['Food Photography', 'Natural Scenes', 'Copilot Integrated', 'Lighting Effects'],
    tags: ['realistic', 'fast', 'microsoft'],
    link: 'https://microsoft.com'
  },
  {
    id: 'adobe-firefly-5',
    name: 'Firefly Image 5',
    developer: 'Adobe',
    releaseDate: '2025-10',
    category: 'Image',
    price: '$9.99/mo',
    apiPrice: 'Credit System',
    description: 'Studio-quality photorealistic image generation with native 4MP resolution and full commercial safety.',
    features: ['4MP Native', 'Photorealistic', 'Commercial Safe', 'Text Rendering'],
    tags: ['professional', 'editing', 'studio'],
    link: 'https://firefly.adobe.com'
  },
  {
    id: 'gpt-4o-image',
    name: 'GPT-4o Image',
    developer: 'OpenAI',
    releaseDate: '2025-03',
    category: 'Image',
    price: '$20/mo',
    apiPrice: '$0.04 / image',
    description: 'Autoregressive architecture with exceptional text rendering and native multimodal capabilities.',
    features: ['Text Rendering', 'Prompt Adherence', 'Multimodal', 'ChatGPT Integrated'],
    tags: ['text', 'realistic', 'assistant'],
    link: 'https://openai.com'
  },
  {
    id: 'reve-image',
    name: 'Reve Image',
    developer: 'Various',
    releaseDate: '2025-03',
    category: 'Image',
    price: '$15/mo',
    apiPrice: '$0.03 / image',
    description: 'Best-in-class prompt adherence with exceptional handling of complex multi-element compositions.',
    features: ['Prompt Adherence', 'Complex Composition', 'Multi-Element', 'High Detail'],
    tags: ['precise', 'realistic'],
    link: '#'
  },
  {
    id: 'ideogram-3',
    name: 'Ideogram 3.0',
    developer: 'Ideogram',
    releaseDate: '2025-03',
    category: 'Image',
    price: '$7/mo',
    apiPrice: '$0.08 / image',
    description: 'Enhanced photorealism with exceptional text rendering. Now includes a canvas editor for batch generation.',
    features: ['Typography', 'Canvas Editor', 'Batch Gen', 'Style Reference'],
    tags: ['design', 'text', 'layout'],
    link: 'https://ideogram.ai'
  },
  {
    id: 'imagen-4',
    name: 'Imagen 4',
    developer: 'Google',
    releaseDate: '2025-02',
    category: 'Image',
    price: '$0.04/img',
    apiPrice: '$0.04 / image',
    description: 'Google’s diffusion-based model with sharp visuals and accurate text rendering. Free tier in AI Studio.',
    features: ['Sharp Visuals', 'Text Rendering', 'Graphic Gen', 'SynthID'],
    tags: ['realistic', 'google', 'text'],
    link: 'https://deepmind.google/technologies/imagen/'
  },

  // --- VIDEO MODELS ---
  {
    id: 'veo-3.1',
    name: 'Veo 3.1',
    developer: 'Google DeepMind',
    releaseDate: '2025-10',
    category: 'Video',
    price: '$0.40/sec',
    apiPrice: '$0.40 / sec',
    description: 'Enhanced creative control with native audio generation, multi-shot sequencing, and character consistency.',
    features: ['Native Audio', 'Multi-Shot', 'Character Consistency', 'Precise Editing'],
    badge: 'Cinema Grade',
    tags: ['video', 'audio', 'editing', 'google'],
    link: 'https://deepmind.google/technologies/veo/'
  },
  {
    id: 'veo-3-fast',
    name: 'Veo 3 Fast',
    developer: 'Google DeepMind',
    releaseDate: '2025-09',
    category: 'Video',
    price: '$0.10/sec',
    apiPrice: '$0.15 / sec',
    description: 'Optimized for speed and integrated into YouTube Shorts. Motion application and video restyling.',
    features: ['Audio Sync', 'YouTube Integration', 'Motion App', 'Fast Gen'],
    tags: ['fast', 'social', 'video'],
    link: 'https://youtube.com'
  },
  {
    id: 'sora-2',
    name: 'Sora 2',
    developer: 'OpenAI',
    releaseDate: '2025-01',
    category: 'Video',
    price: '$20/mo',
    apiPrice: '$0.10 / sec',
    description: 'Industry-leading photorealistic video up to 1 minute. Cinematic B-Roll and storyboard interface.',
    features: ['1 Minute Gen', 'Hyper-Realistic', 'Storyboard', 'Cinematic'],
    badge: 'Photorealism',
    tags: ['cinematic', 'realistic', 'professional'],
    link: 'https://openai.com/sora'
  },
  {
    id: 'runway-gen-4',
    name: 'Runway Gen-4',
    developer: 'Runway AI',
    releaseDate: '2024-11',
    category: 'Video',
    price: '$12/mo',
    apiPrice: '$0.05 / sec',
    description: 'Professional controls for filmmakers. Camera pathing, director mode, and advanced zoom/tilt controls.',
    features: ['Director Mode', 'Camera Control', 'Lip-Sync', '24 FPS'],
    tags: ['professional', 'editing', 'control'],
    link: 'https://runwayml.com'
  },
  {
    id: 'runway-aleph',
    name: 'Runway Aleph',
    developer: 'Runway AI',
    releaseDate: '2025-10',
    category: 'Video',
    price: '$12/mo',
    apiPrice: '$0.08 / sec',
    description: 'State-of-the-art in-context video editing for real footage. Weather alteration and environment changes.',
    features: ['Real Footage Edit', 'Style Transfer', 'Object Removal', 'Green Screen'],
    tags: ['vfx', 'editing', 'professional'],
    link: 'https://runwayml.com'
  },
  {
    id: 'kling-2.1',
    name: 'Kling 2.1',
    developer: 'Kuaishou AI',
    releaseDate: '2025-06',
    category: 'Video',
    price: '$10/mo',
    apiPrice: '$0.10 / sec',
    description: 'High-resolution video up to 2 minutes with realistic physics. Dynamic cameras and multi-shot capabilities.',
    features: ['2 Minute Gen', 'Physics', '1080p', 'Dynamic Camera'],
    tags: ['long-form', 'physics', 'realistic'],
    link: 'https://klingai.com'
  },
  {
    id: 'luma-dream-machine',
    name: 'Luma Dream Machine',
    developer: 'Luma AI',
    releaseDate: '2025-01',
    category: 'Video',
    price: '$9.99/mo',
    apiPrice: '$0.003 / frame',
    description: 'Lightning-fast video generation with 9 distinct camera angle concepts including drone and POV.',
    features: ['120fps Speed', 'Camera Angles', 'POV Support', 'Motion Control'],
    badge: 'Camera Control',
    tags: ['fast', 'camera-control', 'creative'],
    link: 'https://lumalabs.ai'
  },
  {
    id: 'pika-2.1',
    name: 'Pika 2.1',
    developer: 'Pika Labs',
    releaseDate: '2025-02',
    category: 'Video',
    price: '$10/mo',
    apiPrice: 'N/A',
    description: '1080p HD video with "Pikadditions" for seamless object insertion and social media focus.',
    features: ['1080p HD', 'Object Insertion', 'Scene Integration', 'Social Focused'],
    tags: ['social', 'editing', 'fun'],
    link: 'https://pika.art'
  },
  {
    id: 'hailuo-02',
    name: 'Hailuo 02',
    developer: 'MiniMax',
    releaseDate: '2025-03',
    category: 'Video',
    price: '$12/mo',
    apiPrice: '$0.12 / sec',
    description: 'Large model excelling in realistic physics, choreography, and complex body movements.',
    features: ['Complex Motion', 'Physics', 'Choreography', 'Consistency'],
    tags: ['motion', 'physics', 'dramatic'],
    link: '#'
  },
  {
    id: 'wan-2.2',
    name: 'Wan 2.2',
    developer: 'Alibaba',
    releaseDate: '2025-02',
    category: 'Video',
    price: 'Free (Open Source)',
    apiPrice: 'Self-Host',
    description: 'Open-source video generation with Mixture-of-Experts architecture designed for consumer GPUs.',
    features: ['Open Source', 'MoE Arch', 'Consumer GPU', '720p'],
    tags: ['opensource', 'local', 'efficient'],
    link: 'https://github.com'
  },
  {
    id: 'adobe-firefly-video',
    name: 'Firefly Video',
    developer: 'Adobe',
    releaseDate: '2025-02',
    category: 'Video',
    price: '$9.99/mo',
    apiPrice: 'Credit System',
    description: 'Professional video with camera controls. Integrates seamlessly with Creative Cloud workflows.',
    features: ['Camera Angle', 'Keyframes', 'Commercial Safe', 'Motion Control'],
    tags: ['professional', 'adobe', 'workflow'],
    link: 'https://firefly.adobe.com'
  },
  {
    id: 'seedance-1',
    name: 'Seedance 1.0',
    developer: 'ByteDance',
    releaseDate: '2025-03',
    category: 'Video',
    price: '$15/mo',
    apiPrice: 'N/A',
    description: 'High-quality 1080p video with native multi-shot storytelling and character consistency.',
    features: ['Multi-Shot', 'Storytelling', 'Character Consistency', 'Smooth Motion'],
    tags: ['narrative', 'consistency', 'social'],
    link: '#'
  },
  {
    id: 'mochi-1',
    name: 'Mochi 1',
    developer: 'Genmo AI',
    releaseDate: '2024-10',
    category: 'Video',
    price: 'Free (Open Source)',
    apiPrice: 'Self-Host',
    description: 'Community-driven open source video generation model. Customizable and research-friendly.',
    features: ['Open Source', 'Community Driven', 'Research', 'Customizable'],
    tags: ['opensource', 'dev', 'community'],
    link: 'https://genmo.ai'
  },
  {
    id: 'stable-virtual-camera',
    name: 'Stable Virtual Camera',
    developer: 'Stability AI',
    releaseDate: '2025-03',
    category: 'Video',
    price: '$20/mo',
    apiPrice: '$0.05 / sec',
    description: 'Transforms 2D images into immersive 3D videos with 14 dynamic camera paths.',
    features: ['Image-to-3D', '360 Rotation', 'Dolly Zoom', 'path Control'],
    tags: ['3d', 'conversion', 'camera'],
    link: 'https://stability.ai'
  },

  // --- AUDIO MODELS ---
  {
    id: 'lyria-2',
    name: 'Lyria 2 & RealTime',
    developer: 'Google DeepMind',
    releaseDate: '2025-04',
    category: 'Audio',
    price: 'Free',
    apiPrice: 'Free (Beta)',
    description: 'Real-time music generation with 48 kHz stereo audio. Interactive creation via MusicFX.',
    features: ['Real-Time', '48kHz Stereo', 'Interactive', 'SynthID'],
    badge: 'Real-Time',
    tags: ['music', 'interactive', 'google'],
    link: 'https://aitestkitchen.withgoogle.com'
  },
  {
    id: 'suno-v5',
    name: 'Suno v5',
    developer: 'Suno',
    releaseDate: '2025-09',
    category: 'Audio',
    price: '$10/mo',
    apiPrice: 'N/A',
    description: 'Studio-grade fidelity with natural vocals. Full song generation with lyrics and persona memory.',
    features: ['Full Songs', 'Lyrics', 'Stem Split', 'Personas'],
    badge: 'Studio Grade',
    tags: ['music', 'vocals', 'production'],
    link: 'https://suno.com'
  },
  {
    id: 'eleven-music',
    name: 'Eleven Music',
    developer: 'ElevenLabs',
    releaseDate: '2025-08',
    category: 'Audio',
    price: '$11/mo',
    apiPrice: '$0.50 / min',
    description: 'Industry-leading vocal synthesis with music generation. Strong instrumentals and commercial rights.',
    features: ['Vocal Synthesis', 'Instrumentals', 'Commercial Use', 'High Fidelity'],
    tags: ['vocals', 'sfx', 'production'],
    link: 'https://elevenlabs.io'
  },
  {
    id: 'beatoven-maestro',
    name: 'Beatoven Maestro',
    developer: 'Beatoven.ai',
    releaseDate: '2025-08',
    category: 'Audio',
    price: '$15/mo',
    apiPrice: '$0.20 / min',
    description: 'Ethically trained on licensed music, compensating rights-holders. Adaptive background scoring.',
    features: ['Ethical AI', 'Royalty Free', 'Licensed Data', 'Adaptive'],
    tags: ['ethical', 'background', 'music'],
    link: 'https://beatoven.ai'
  }
];
